const ReleaseStatus = Object.freeze({
  CREATED: 'CREATED',
  VALIDATING: 'VALIDATING',
  READY_FOR_STAGING: 'READY_FOR_STAGING',
  DEPLOYING_STAGING: 'DEPLOYING_STAGING',
  VERIFYING_STAGING: 'VERIFYING_STAGING',
  READY_FOR_PRODUCTION: 'READY_FOR_PRODUCTION',
  AWAITING_PRODUCTION_APPROVAL: 'AWAITING_PRODUCTION_APPROVAL',
  DEPLOYING_PRODUCTION: 'DEPLOYING_PRODUCTION',
  VERIFYING_PRODUCTION: 'VERIFYING_PRODUCTION',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  ROLLBACK_QUEUED: 'ROLLBACK_QUEUED',
  ROLLING_BACK: 'ROLLING_BACK',
  ROLLED_BACK: 'ROLLED_BACK'
});

module.exports = { ReleaseStatus };
